Imports System.Data


public class DIR_ESTABLECIMIENTOCREADODAT

#REGION "METODO INGRESO"

   Public Sub Insertar(byval DIR_ESTABLECIMIENTOCREADO as DIR_ESTABLECIMIENTOCREADOENT )
       Try
           Dim sp As New StoredProcedure_class("SP_DIR_ESTABLECIMIENTOCREADO_Insertar")
           sp.AgregarParametro("ID_ENCUESTA",DIR_ESTABLECIMIENTOCREADO.ID_ENCUESTA)
           sp.AgregarParametro("ROL",DIR_ESTABLECIMIENTOCREADO.ROL)
           sp.AgregarParametro("DVROL",DIR_ESTABLECIMIENTOCREADO.DVROL)
           sp.AgregarParametro("RUT",DIR_ESTABLECIMIENTOCREADO.RUT)
           sp.AgregarParametro("NUI",DIR_ESTABLECIMIENTOCREADO.NUI)
           sp.AgregarParametro("DVNUI",DIR_ESTABLECIMIENTOCREADO.DVNUI)
           sp.AgregarParametro("CIIU",DIR_ESTABLECIMIENTOCREADO.CIIU)
           sp.AgregarParametro("REGION_E",DIR_ESTABLECIMIENTOCREADO.REGION_E)
           sp.AgregarParametro("PROVINCIA_E",DIR_ESTABLECIMIENTOCREADO.PROVINCIA_E)
           sp.AgregarParametro("COMUNA_E",DIR_ESTABLECIMIENTOCREADO.COMUNA_E)
           sp.AgregarParametro("GLOSA_COMUNA_E",DIR_ESTABLECIMIENTOCREADO.GLOSA_COMUNA_E)
           sp.AgregarParametro("CALLE_E",DIR_ESTABLECIMIENTOCREADO.CALLE_E)
           sp.AgregarParametro("NRO_E",DIR_ESTABLECIMIENTOCREADO.NRO_E)
           sp.AgregarParametro("NRO_LOCAL_E",DIR_ESTABLECIMIENTOCREADO.NRO_LOCAL_E)
           sp.AgregarParametro("CODA_FONO_E",DIR_ESTABLECIMIENTOCREADO.CODA_FONO_E)
           sp.AgregarParametro("FONO_E",DIR_ESTABLECIMIENTOCREADO.FONO_E)
           sp.AgregarParametro("CODA_FAX_E",DIR_ESTABLECIMIENTOCREADO.CODA_FAX_E)
           sp.AgregarParametro("FAX_E",DIR_ESTABLECIMIENTOCREADO.FAX_E)
           sp.AgregarParametro("EMAIL_E",DIR_ESTABLECIMIENTOCREADO.EMAIL_E)
           sp.AgregarParametro("WEB_E",DIR_ESTABLECIMIENTOCREADO.WEB_E)
           sp.AgregarParametro("CASILLA_COMERCIAL",DIR_ESTABLECIMIENTOCREADO.CASILLA_COMERCIAL)
           sp.AgregarParametro("NOMBREESTABLECIMIENTO",DIR_ESTABLECIMIENTOCREADO.NOMBREESTABLECIMIENTO)
           sp.AgregarParametro("TIPO_ESTABLECIMIENTO",DIR_ESTABLECIMIENTOCREADO.TIPO_ESTABLECIMIENTO)
           sp.AgregarParametro("TIPO_FUNCIONAMIENTO",DIR_ESTABLECIMIENTOCREADO.TIPO_FUNCIONAMIENTO)
            sp.AgregarParametro("CLASE", DIR_ESTABLECIMIENTOCREADO.CLASE)
           sp.AgregarParametro("EXROL",DIR_ESTABLECIMIENTOCREADO.EXROL)
           sp.AgregarParametro("HABITACIONES_UNIDADES_HABITACIONALES",DIR_ESTABLECIMIENTOCREADO.HABITACIONES_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("HABITACIONES_CAPACIDAD_MAXIMA",DIR_ESTABLECIMIENTOCREADO.HABITACIONES_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("CABANAS_UNIDADES_HABITACIONALES",DIR_ESTABLECIMIENTOCREADO.CABANAS_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("CABANAS_CAPACIDAD_MAXIMA",DIR_ESTABLECIMIENTOCREADO.CABANAS_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("DEPARTAMENTOS_UNIDADES_HABITACIONALES",DIR_ESTABLECIMIENTOCREADO.DEPARTAMENTOS_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("DEPARTAMENTOS_CAPACIDAD_MAXIMA",DIR_ESTABLECIMIENTOCREADO.DEPARTAMENTOS_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("SITIOSDECAMPING_UNIDADES_HABITACIONALES",DIR_ESTABLECIMIENTOCREADO.SITIOSDECAMPING_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("SITIOSDECAMPING_CAPACIDAD_MAXIMA",DIR_ESTABLECIMIENTOCREADO.SITIOSDECAMPING_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("TOTAL_UNIDADES_HABITACIONALES",DIR_ESTABLECIMIENTOCREADO.TOTAL_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("TOTAL_CAPACIDAD_MAXIMA",DIR_ESTABLECIMIENTOCREADO.TOTAL_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("PERSONAL_OCUPADO_PERMANENTE_HOMBRE",DIR_ESTABLECIMIENTOCREADO.PERSONAL_OCUPADO_PERMANENTE_HOMBRE)
           sp.AgregarParametro("PERSONAL_OCUPADO_PERMANENTE_MUJER",DIR_ESTABLECIMIENTOCREADO.PERSONAL_OCUPADO_PERMANENTE_MUJER)
           sp.AgregarParametro("PERSONAL_OCUPADO_EVENTUAL_HOMBRE",DIR_ESTABLECIMIENTOCREADO.PERSONAL_OCUPADO_EVENTUAL_HOMBRE)
           sp.AgregarParametro("PERSONAL_OCUPADO_EVENTUAL_MUJER",DIR_ESTABLECIMIENTOCREADO.PERSONAL_OCUPADO_EVENTUAL_MUJER)
           sp.AgregarParametro("TOTAL_PERSONAL_OCUPADO_HOMBRE",DIR_ESTABLECIMIENTOCREADO.TOTAL_PERSONAL_OCUPADO_HOMBRE)
           sp.AgregarParametro("TOTAL_PERSONAL_OCUPADO_MUJER",DIR_ESTABLECIMIENTOCREADO.TOTAL_PERSONAL_OCUPADO_MUJER)
           sp.AgregarParametro("TOTAL_PERSONAL_OCUPADO",DIR_ESTABLECIMIENTOCREADO.TOTAL_PERSONAL_OCUPADO)
           sp.AgregarParametro("FECHA_CREACION",DIR_ESTABLECIMIENTOCREADO.FECHA_CREACION)
           sp.AgregarParametro("USUARIO_CREACION",DIR_ESTABLECIMIENTOCREADO.USUARIO_CREACION)
           sp.EjecutarProcedimiento()
       Catch ex As Exception
           Throw New Exception(ex.Message)
       End Try
   End Sub
#End Region
#REGION "METODO ACTUALIZAR"

   Public Sub Actualizar(byval DIR_ESTABLECIMIENTOCREADO as DIR_ESTABLECIMIENTOCREADOENT )
       Try
           Dim sp As New StoredProcedure_class("SP_DIR_ESTABLECIMIENTOCREADO_Actualizar")
           sp.AgregarParametro("ID_ENCUESTA",DIR_ESTABLECIMIENTOCREADO.ID_ENCUESTA)
           sp.AgregarParametro("ROL",DIR_ESTABLECIMIENTOCREADO.ROL)
           sp.AgregarParametro("DVROL",DIR_ESTABLECIMIENTOCREADO.DVROL)
           sp.AgregarParametro("RUT",DIR_ESTABLECIMIENTOCREADO.RUT)
           sp.AgregarParametro("NUI",DIR_ESTABLECIMIENTOCREADO.NUI)
           sp.AgregarParametro("DVNUI",DIR_ESTABLECIMIENTOCREADO.DVNUI)
           sp.AgregarParametro("CIIU",DIR_ESTABLECIMIENTOCREADO.CIIU)
           sp.AgregarParametro("REGION_E",DIR_ESTABLECIMIENTOCREADO.REGION_E)
           sp.AgregarParametro("PROVINCIA_E",DIR_ESTABLECIMIENTOCREADO.PROVINCIA_E)
           sp.AgregarParametro("COMUNA_E",DIR_ESTABLECIMIENTOCREADO.COMUNA_E)
           sp.AgregarParametro("GLOSA_COMUNA_E",DIR_ESTABLECIMIENTOCREADO.GLOSA_COMUNA_E)
           sp.AgregarParametro("CALLE_E",DIR_ESTABLECIMIENTOCREADO.CALLE_E)
           sp.AgregarParametro("NRO_E",DIR_ESTABLECIMIENTOCREADO.NRO_E)
           sp.AgregarParametro("NRO_LOCAL_E",DIR_ESTABLECIMIENTOCREADO.NRO_LOCAL_E)
           sp.AgregarParametro("CODA_FONO_E",DIR_ESTABLECIMIENTOCREADO.CODA_FONO_E)
           sp.AgregarParametro("FONO_E",DIR_ESTABLECIMIENTOCREADO.FONO_E)
           sp.AgregarParametro("CODA_FAX_E",DIR_ESTABLECIMIENTOCREADO.CODA_FAX_E)
           sp.AgregarParametro("FAX_E",DIR_ESTABLECIMIENTOCREADO.FAX_E)
           sp.AgregarParametro("EMAIL_E",DIR_ESTABLECIMIENTOCREADO.EMAIL_E)
           sp.AgregarParametro("WEB_E",DIR_ESTABLECIMIENTOCREADO.WEB_E)
           sp.AgregarParametro("CASILLA_COMERCIAL",DIR_ESTABLECIMIENTOCREADO.CASILLA_COMERCIAL)
           sp.AgregarParametro("NOMBREESTABLECIMIENTO",DIR_ESTABLECIMIENTOCREADO.NOMBREESTABLECIMIENTO)
           sp.AgregarParametro("TIPO_ESTABLECIMIENTO",DIR_ESTABLECIMIENTOCREADO.TIPO_ESTABLECIMIENTO)
           sp.AgregarParametro("TIPO_FUNCIONAMIENTO",DIR_ESTABLECIMIENTOCREADO.TIPO_FUNCIONAMIENTO)
            sp.AgregarParametro("CLASE", DIR_ESTABLECIMIENTOCREADO.CLASE)
           sp.AgregarParametro("EXROL",DIR_ESTABLECIMIENTOCREADO.EXROL)
           sp.AgregarParametro("HABITACIONES_UNIDADES_HABITACIONALES",DIR_ESTABLECIMIENTOCREADO.HABITACIONES_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("HABITACIONES_CAPACIDAD_MAXIMA",DIR_ESTABLECIMIENTOCREADO.HABITACIONES_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("CABANAS_UNIDADES_HABITACIONALES",DIR_ESTABLECIMIENTOCREADO.CABANAS_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("CABANAS_CAPACIDAD_MAXIMA",DIR_ESTABLECIMIENTOCREADO.CABANAS_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("DEPARTAMENTOS_UNIDADES_HABITACIONALES",DIR_ESTABLECIMIENTOCREADO.DEPARTAMENTOS_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("DEPARTAMENTOS_CAPACIDAD_MAXIMA",DIR_ESTABLECIMIENTOCREADO.DEPARTAMENTOS_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("SITIOSDECAMPING_UNIDADES_HABITACIONALES",DIR_ESTABLECIMIENTOCREADO.SITIOSDECAMPING_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("SITIOSDECAMPING_CAPACIDAD_MAXIMA",DIR_ESTABLECIMIENTOCREADO.SITIOSDECAMPING_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("TOTAL_UNIDADES_HABITACIONALES",DIR_ESTABLECIMIENTOCREADO.TOTAL_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("TOTAL_CAPACIDAD_MAXIMA",DIR_ESTABLECIMIENTOCREADO.TOTAL_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("PERSONAL_OCUPADO_PERMANENTE_HOMBRE",DIR_ESTABLECIMIENTOCREADO.PERSONAL_OCUPADO_PERMANENTE_HOMBRE)
           sp.AgregarParametro("PERSONAL_OCUPADO_PERMANENTE_MUJER",DIR_ESTABLECIMIENTOCREADO.PERSONAL_OCUPADO_PERMANENTE_MUJER)
           sp.AgregarParametro("PERSONAL_OCUPADO_EVENTUAL_HOMBRE",DIR_ESTABLECIMIENTOCREADO.PERSONAL_OCUPADO_EVENTUAL_HOMBRE)
           sp.AgregarParametro("PERSONAL_OCUPADO_EVENTUAL_MUJER",DIR_ESTABLECIMIENTOCREADO.PERSONAL_OCUPADO_EVENTUAL_MUJER)
           sp.AgregarParametro("TOTAL_PERSONAL_OCUPADO_HOMBRE",DIR_ESTABLECIMIENTOCREADO.TOTAL_PERSONAL_OCUPADO_HOMBRE)
           sp.AgregarParametro("TOTAL_PERSONAL_OCUPADO_MUJER",DIR_ESTABLECIMIENTOCREADO.TOTAL_PERSONAL_OCUPADO_MUJER)
           sp.AgregarParametro("TOTAL_PERSONAL_OCUPADO",DIR_ESTABLECIMIENTOCREADO.TOTAL_PERSONAL_OCUPADO)
           sp.AgregarParametro("FECHA_CREACION",DIR_ESTABLECIMIENTOCREADO.FECHA_CREACION)
           sp.AgregarParametro("USUARIO_CREACION",DIR_ESTABLECIMIENTOCREADO.USUARIO_CREACION)
           sp.EjecutarProcedimiento()
       Catch ex As Exception
           Throw New Exception(ex.Message)
       End Try
   End Sub
#End Region
#REGION "METODO ELIMINAR"

   Public Sub Eliminar( PARAMETROS )
       Try
           Dim sp As New StoredProcedure_class("SP_DIR_ESTABLECIMIENTOCREADO_Eliminar")
'Aqui deben definir los parametros necesarios
           sp.AgregarParametro("","")
'Fin de parametros necesarios
           sp.EjecutarProcedimiento()
       Catch ex As Exception
           Throw New Exception(ex.Message)
       End Try
   End Sub

#END REGION
#REGION "METODO LISTAR"

   Public Function Listar() as DIR_ESTABLECIMIENTOCREADOENT()
       Try
           Dim dr as DataRow
           Dim dt as DataTable
           Dim i as Integer
           Dim sp As New StoredProcedure_class("SP_DIR_ESTABLECIMIENTOCREADO_Listar")
           dt = sp.EjecutarProcedimiento().tables(0)
           Dim DIR_ESTABLECIMIENTOCREADO(dt.Rows.count() - 1) as DIR_ESTABLECIMIENTOCREADOENT
           i = 0
           for each dr in dt.rows
                DIR_ESTABLECIMIENTOCREADO(i) = New DIR_ESTABLECIMIENTOCREADOENT()
                DIR_ESTABLECIMIENTOCREADO(i).ID_ENCUESTA = dr("ID_ENCUESTA")
                DIR_ESTABLECIMIENTOCREADO(i).ROL = dr("ROL")
                DIR_ESTABLECIMIENTOCREADO(i).DVROL = dr("DVROL")
                DIR_ESTABLECIMIENTOCREADO(i).RUT = dr("RUT")
                DIR_ESTABLECIMIENTOCREADO(i).NUI = dr("NUI")
                DIR_ESTABLECIMIENTOCREADO(i).DVNUI = dr("DVNUI")
                DIR_ESTABLECIMIENTOCREADO(i).CIIU = dr("CIIU")
                DIR_ESTABLECIMIENTOCREADO(i).REGION_E = dr("REGION_E")
                DIR_ESTABLECIMIENTOCREADO(i).PROVINCIA_E = dr("PROVINCIA_E")
                DIR_ESTABLECIMIENTOCREADO(i).COMUNA_E = dr("COMUNA_E")
                DIR_ESTABLECIMIENTOCREADO(i).GLOSA_COMUNA_E = dr("GLOSA_COMUNA_E")
                DIR_ESTABLECIMIENTOCREADO(i).CALLE_E = dr("CALLE_E")
                DIR_ESTABLECIMIENTOCREADO(i).NRO_E = dr("NRO_E")
                DIR_ESTABLECIMIENTOCREADO(i).NRO_LOCAL_E = dr("NRO_LOCAL_E")
                DIR_ESTABLECIMIENTOCREADO(i).CODA_FONO_E = dr("CODA_FONO_E")
                DIR_ESTABLECIMIENTOCREADO(i).FONO_E = dr("FONO_E")
                DIR_ESTABLECIMIENTOCREADO(i).CODA_FAX_E = dr("CODA_FAX_E")
                DIR_ESTABLECIMIENTOCREADO(i).FAX_E = dr("FAX_E")
                DIR_ESTABLECIMIENTOCREADO(i).EMAIL_E = dr("EMAIL_E")
                DIR_ESTABLECIMIENTOCREADO(i).WEB_E = dr("WEB_E")
                DIR_ESTABLECIMIENTOCREADO(i).CASILLA_COMERCIAL = dr("CASILLA_COMERCIAL")
                DIR_ESTABLECIMIENTOCREADO(i).NOMBREESTABLECIMIENTO = dr("NOMBREESTABLECIMIENTO")
                DIR_ESTABLECIMIENTOCREADO(i).TIPO_ESTABLECIMIENTO = dr("TIPO_ESTABLECIMIENTO")
                DIR_ESTABLECIMIENTOCREADO(i).TIPO_FUNCIONAMIENTO = dr("TIPO_FUNCIONAMIENTO")
                DIR_ESTABLECIMIENTOCREADO(i).CLASE = dr("CLASE")
                DIR_ESTABLECIMIENTOCREADO(i).EXROL = dr("EXROL")
                DIR_ESTABLECIMIENTOCREADO(i).HABITACIONES_UNIDADES_HABITACIONALES = dr("HABITACIONES_UNIDADES_HABITACIONALES")
                DIR_ESTABLECIMIENTOCREADO(i).HABITACIONES_CAPACIDAD_MAXIMA = dr("HABITACIONES_CAPACIDAD_MAXIMA")
                DIR_ESTABLECIMIENTOCREADO(i).CABANAS_UNIDADES_HABITACIONALES = dr("CABANAS_UNIDADES_HABITACIONALES")
                DIR_ESTABLECIMIENTOCREADO(i).CABANAS_CAPACIDAD_MAXIMA = dr("CABANAS_CAPACIDAD_MAXIMA")
                DIR_ESTABLECIMIENTOCREADO(i).DEPARTAMENTOS_UNIDADES_HABITACIONALES = dr("DEPARTAMENTOS_UNIDADES_HABITACIONALES")
                DIR_ESTABLECIMIENTOCREADO(i).DEPARTAMENTOS_CAPACIDAD_MAXIMA = dr("DEPARTAMENTOS_CAPACIDAD_MAXIMA")
                DIR_ESTABLECIMIENTOCREADO(i).SITIOSDECAMPING_UNIDADES_HABITACIONALES = dr("SITIOSDECAMPING_UNIDADES_HABITACIONALES")
                DIR_ESTABLECIMIENTOCREADO(i).SITIOSDECAMPING_CAPACIDAD_MAXIMA = dr("SITIOSDECAMPING_CAPACIDAD_MAXIMA")
                DIR_ESTABLECIMIENTOCREADO(i).TOTAL_UNIDADES_HABITACIONALES = dr("TOTAL_UNIDADES_HABITACIONALES")
                DIR_ESTABLECIMIENTOCREADO(i).TOTAL_CAPACIDAD_MAXIMA = dr("TOTAL_CAPACIDAD_MAXIMA")
                DIR_ESTABLECIMIENTOCREADO(i).PERSONAL_OCUPADO_PERMANENTE_HOMBRE = dr("PERSONAL_OCUPADO_PERMANENTE_HOMBRE")
                DIR_ESTABLECIMIENTOCREADO(i).PERSONAL_OCUPADO_PERMANENTE_MUJER = dr("PERSONAL_OCUPADO_PERMANENTE_MUJER")
                DIR_ESTABLECIMIENTOCREADO(i).PERSONAL_OCUPADO_EVENTUAL_HOMBRE = dr("PERSONAL_OCUPADO_EVENTUAL_HOMBRE")
                DIR_ESTABLECIMIENTOCREADO(i).PERSONAL_OCUPADO_EVENTUAL_MUJER = dr("PERSONAL_OCUPADO_EVENTUAL_MUJER")
                DIR_ESTABLECIMIENTOCREADO(i).TOTAL_PERSONAL_OCUPADO_HOMBRE = dr("TOTAL_PERSONAL_OCUPADO_HOMBRE")
                DIR_ESTABLECIMIENTOCREADO(i).TOTAL_PERSONAL_OCUPADO_MUJER = dr("TOTAL_PERSONAL_OCUPADO_MUJER")
                DIR_ESTABLECIMIENTOCREADO(i).TOTAL_PERSONAL_OCUPADO = dr("TOTAL_PERSONAL_OCUPADO")
                DIR_ESTABLECIMIENTOCREADO(i).FECHA_CREACION = dr("FECHA_CREACION")
                DIR_ESTABLECIMIENTOCREADO(i).USUARIO_CREACION = dr("USUARIO_CREACION")
                i = i + 1
           next
           return DIR_ESTABLECIMIENTOCREADO
       Catch ex As Exception
           Throw New Exception(ex.Message)
       End Try
   End Function

    Public Function ListarATabla() As Data.DataTable
        Try
            Dim dt As DataTable
            Dim sp As New StoredProcedure_class("SP_DIR_ESTABLECIMIENTOCREADO_Listar")
            dt = sp.EjecutarProcedimiento().Tables(0)
            Return dt
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Function
#END REGION

#Region "ArchivoExcel, Obtener datos para la insercion del establecimiento en específico"
    Public Function ObtenerDatosParaInsercion(ByVal sp As StoredProcedure_class, ByVal sqlCmd As Data.SqlClient.SqlCommand, ByVal dr As Data.DataRow) As Data.DataRow
        Try
            sp.AgregarParametro("RUT", dr("RUT"))
            sp.AgregarParametro("ROL", dr("ROL"))
            sp.AgregarParametro("DVROL", dr("DV_ROL"))
            Return sp.EjecutarProcedimiento(sqlCmd).Tables(0).Rows(0)
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Function
#End Region

#REGION "CONSTRUCTORES DE LA CLASE"
   Public Sub New()

   End Sub
#END REGION

end class
