Imports System.Data


public class LOG_ESTABLECIMIENTOMODIFICADODAT

#REGION "METODO INGRESO"

   Public Sub Insertar(byval LOG_ESTABLECIMIENTOMODIFICADO as LOG_ESTABLECIMIENTOMODIFICADOENT )
       Try
           Dim sp As New StoredProcedure_class("SP_LOG_ESTABLECIMIENTOMODIFICADO_Insertar")
           sp.AgregarParametro("ID_ENCUESTA",LOG_ESTABLECIMIENTOMODIFICADO.ID_ENCUESTA)
           sp.AgregarParametro("ROL",LOG_ESTABLECIMIENTOMODIFICADO.ROL)
           sp.AgregarParametro("DVROL",LOG_ESTABLECIMIENTOMODIFICADO.DVROL)
           sp.AgregarParametro("ANO",LOG_ESTABLECIMIENTOMODIFICADO.ANO)
           sp.AgregarParametro("PERIODO",LOG_ESTABLECIMIENTOMODIFICADO.PERIODO)
           sp.AgregarParametro("RUT",LOG_ESTABLECIMIENTOMODIFICADO.RUT)
           sp.AgregarParametro("NUI",LOG_ESTABLECIMIENTOMODIFICADO.NUI)
           sp.AgregarParametro("DVNUI",LOG_ESTABLECIMIENTOMODIFICADO.DVNUI)
           sp.AgregarParametro("CIIU",LOG_ESTABLECIMIENTOMODIFICADO.CIIU)
           sp.AgregarParametro("REGION_E",LOG_ESTABLECIMIENTOMODIFICADO.REGION_E)
           sp.AgregarParametro("PROVINCIA_E",LOG_ESTABLECIMIENTOMODIFICADO.PROVINCIA_E)
           sp.AgregarParametro("COMUNA_E",LOG_ESTABLECIMIENTOMODIFICADO.COMUNA_E)
           sp.AgregarParametro("GLOSA_COMUNA_E",LOG_ESTABLECIMIENTOMODIFICADO.GLOSA_COMUNA_E)
           sp.AgregarParametro("CALLE_E",LOG_ESTABLECIMIENTOMODIFICADO.CALLE_E)
           sp.AgregarParametro("NRO_E",LOG_ESTABLECIMIENTOMODIFICADO.NRO_E)
           sp.AgregarParametro("NRO_LOCAL_E",LOG_ESTABLECIMIENTOMODIFICADO.NRO_LOCAL_E)
           sp.AgregarParametro("CODA_FONO_E",LOG_ESTABLECIMIENTOMODIFICADO.CODA_FONO_E)
           sp.AgregarParametro("FONO_E",LOG_ESTABLECIMIENTOMODIFICADO.FONO_E)
           sp.AgregarParametro("CODA_FAX_E",LOG_ESTABLECIMIENTOMODIFICADO.CODA_FAX_E)
           sp.AgregarParametro("FAX_E",LOG_ESTABLECIMIENTOMODIFICADO.FAX_E)
           sp.AgregarParametro("EMAIL_E",LOG_ESTABLECIMIENTOMODIFICADO.EMAIL_E)
           sp.AgregarParametro("WEB_E",LOG_ESTABLECIMIENTOMODIFICADO.WEB_E)
           sp.AgregarParametro("CASILLA_COMERCIAL",LOG_ESTABLECIMIENTOMODIFICADO.CASILLA_COMERCIAL)
           sp.AgregarParametro("NOMBREESTABLECIMIENTO",LOG_ESTABLECIMIENTOMODIFICADO.NOMBREESTABLECIMIENTO)
           sp.AgregarParametro("TIPO_ESTABLECIMIENTO",LOG_ESTABLECIMIENTOMODIFICADO.TIPO_ESTABLECIMIENTO)
           sp.AgregarParametro("TIPO_FUNCIONAMIENTO",LOG_ESTABLECIMIENTOMODIFICADO.TIPO_FUNCIONAMIENTO)
            sp.AgregarParametro("CLASE", LOG_ESTABLECIMIENTOMODIFICADO.CLASE)
           sp.AgregarParametro("EXROL",LOG_ESTABLECIMIENTOMODIFICADO.EXROL)
           sp.AgregarParametro("NOMBRE_INFORMANTE",LOG_ESTABLECIMIENTOMODIFICADO.NOMBRE_INFORMANTE)
           sp.AgregarParametro("CARGO_INFORMANTE",LOG_ESTABLECIMIENTOMODIFICADO.CARGO_INFORMANTE)
           sp.AgregarParametro("CODA_FONO_INFORMANTE",LOG_ESTABLECIMIENTOMODIFICADO.CODA_FONO_INFORMANTE)
           sp.AgregarParametro("FONO_INFORMANTE",LOG_ESTABLECIMIENTOMODIFICADO.FONO_INFORMANTE)
           sp.AgregarParametro("CELULAR_INFORMANTE",LOG_ESTABLECIMIENTOMODIFICADO.CELULAR_INFORMANTE)
           sp.AgregarParametro("EMAIL_INFORMANTE",LOG_ESTABLECIMIENTOMODIFICADO.EMAIL_INFORMANTE)
           sp.AgregarParametro("NOMBRE_JEFE_RESPONSABLE",LOG_ESTABLECIMIENTOMODIFICADO.NOMBRE_JEFE_RESPONSABLE)
           sp.AgregarParametro("HABITACIONES_UNIDADES_HABITACIONALES",LOG_ESTABLECIMIENTOMODIFICADO.HABITACIONES_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("HABITACIONES_CAPACIDAD_MAXIMA",LOG_ESTABLECIMIENTOMODIFICADO.HABITACIONES_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("CABANAS_UNIDADES_HABITACIONALES",LOG_ESTABLECIMIENTOMODIFICADO.CABANAS_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("CABANAS_CAPACIDAD_MAXIMA",LOG_ESTABLECIMIENTOMODIFICADO.CABANAS_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("DEPARTAMENTOS_UNIDADES_HABITACIONALES",LOG_ESTABLECIMIENTOMODIFICADO.DEPARTAMENTOS_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("DEPARTAMENTOS_CAPACIDAD_MAXIMA",LOG_ESTABLECIMIENTOMODIFICADO.DEPARTAMENTOS_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("SITIOSDECAMPING_UNIDADES_HABITACIONALES",LOG_ESTABLECIMIENTOMODIFICADO.SITIOSDECAMPING_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("SITIOSDECAMPING_CAPACIDAD_MAXIMA",LOG_ESTABLECIMIENTOMODIFICADO.SITIOSDECAMPING_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("TOTAL_UNIDADES_HABITACIONALES",LOG_ESTABLECIMIENTOMODIFICADO.TOTAL_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("TOTAL_CAPACIDAD_MAXIMA",LOG_ESTABLECIMIENTOMODIFICADO.TOTAL_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("PERSONAL_OCUPADO_PERMANENTE_HOMBRE",LOG_ESTABLECIMIENTOMODIFICADO.PERSONAL_OCUPADO_PERMANENTE_HOMBRE)
           sp.AgregarParametro("PERSONAL_OCUPADO_PERMANENTE_MUJER",LOG_ESTABLECIMIENTOMODIFICADO.PERSONAL_OCUPADO_PERMANENTE_MUJER)
           sp.AgregarParametro("PERSONAL_OCUPADO_EVENTUAL_HOMBRE",LOG_ESTABLECIMIENTOMODIFICADO.PERSONAL_OCUPADO_EVENTUAL_HOMBRE)
           sp.AgregarParametro("PERSONAL_OCUPADO_EVENTUAL_MUJER",LOG_ESTABLECIMIENTOMODIFICADO.PERSONAL_OCUPADO_EVENTUAL_MUJER)
           sp.AgregarParametro("TOTAL_PERSONAL_OCUPADO_HOMBRE",LOG_ESTABLECIMIENTOMODIFICADO.TOTAL_PERSONAL_OCUPADO_HOMBRE)
           sp.AgregarParametro("TOTAL_PERSONAL_OCUPADO_MUJER",LOG_ESTABLECIMIENTOMODIFICADO.TOTAL_PERSONAL_OCUPADO_MUJER)
           sp.AgregarParametro("TOTAL_PERSONAL_OCUPADO",LOG_ESTABLECIMIENTOMODIFICADO.TOTAL_PERSONAL_OCUPADO)
            sp.AgregarParametro("FECHA_LEVANTAMIENTO", LOG_ESTABLECIMIENTOMODIFICADO.FECHA_LEVANTAMIENTO)
            'sp.AgregarParametro("FECHA_LEVANTAMIENTO", IIf(LOG_ESTABLECIMIENTOMODIFICADO.FECHA_LEVANTAMIENTO Is "", DBNull.Value, LOG_ESTABLECIMIENTOMODIFICADO.FECHA_LEVANTAMIENTO))
            sp.AgregarParametro("USUARIO_ACTUALIZACION", LOG_ESTABLECIMIENTOMODIFICADO.USUARIO_ACTUALIZACION)
           sp.AgregarParametro("FECHA_ACTUALIZACION",LOG_ESTABLECIMIENTOMODIFICADO.FECHA_ACTUALIZACION)
           sp.EjecutarProcedimiento()
       Catch ex As Exception
           Throw New Exception(ex.Message)
       End Try
   End Sub
#End Region
#REGION "METODO ACTUALIZAR"

   Public Sub Actualizar(byval LOG_ESTABLECIMIENTOMODIFICADO as LOG_ESTABLECIMIENTOMODIFICADOENT )
       Try
           Dim sp As New StoredProcedure_class("SP_LOG_ESTABLECIMIENTOMODIFICADO_Actualizar")
           sp.AgregarParametro("ID_ENCUESTA",LOG_ESTABLECIMIENTOMODIFICADO.ID_ENCUESTA)
           sp.AgregarParametro("ROL",LOG_ESTABLECIMIENTOMODIFICADO.ROL)
           sp.AgregarParametro("DVROL",LOG_ESTABLECIMIENTOMODIFICADO.DVROL)
           sp.AgregarParametro("ANO",LOG_ESTABLECIMIENTOMODIFICADO.ANO)
           sp.AgregarParametro("PERIODO",LOG_ESTABLECIMIENTOMODIFICADO.PERIODO)
           sp.AgregarParametro("RUT",LOG_ESTABLECIMIENTOMODIFICADO.RUT)
           sp.AgregarParametro("NUI",LOG_ESTABLECIMIENTOMODIFICADO.NUI)
           sp.AgregarParametro("DVNUI",LOG_ESTABLECIMIENTOMODIFICADO.DVNUI)
           sp.AgregarParametro("CIIU",LOG_ESTABLECIMIENTOMODIFICADO.CIIU)
           sp.AgregarParametro("REGION_E",LOG_ESTABLECIMIENTOMODIFICADO.REGION_E)
           sp.AgregarParametro("PROVINCIA_E",LOG_ESTABLECIMIENTOMODIFICADO.PROVINCIA_E)
           sp.AgregarParametro("COMUNA_E",LOG_ESTABLECIMIENTOMODIFICADO.COMUNA_E)
           sp.AgregarParametro("GLOSA_COMUNA_E",LOG_ESTABLECIMIENTOMODIFICADO.GLOSA_COMUNA_E)
           sp.AgregarParametro("CALLE_E",LOG_ESTABLECIMIENTOMODIFICADO.CALLE_E)
           sp.AgregarParametro("NRO_E",LOG_ESTABLECIMIENTOMODIFICADO.NRO_E)
           sp.AgregarParametro("NRO_LOCAL_E",LOG_ESTABLECIMIENTOMODIFICADO.NRO_LOCAL_E)
           sp.AgregarParametro("CODA_FONO_E",LOG_ESTABLECIMIENTOMODIFICADO.CODA_FONO_E)
           sp.AgregarParametro("FONO_E",LOG_ESTABLECIMIENTOMODIFICADO.FONO_E)
           sp.AgregarParametro("CODA_FAX_E",LOG_ESTABLECIMIENTOMODIFICADO.CODA_FAX_E)
           sp.AgregarParametro("FAX_E",LOG_ESTABLECIMIENTOMODIFICADO.FAX_E)
           sp.AgregarParametro("EMAIL_E",LOG_ESTABLECIMIENTOMODIFICADO.EMAIL_E)
           sp.AgregarParametro("WEB_E",LOG_ESTABLECIMIENTOMODIFICADO.WEB_E)
           sp.AgregarParametro("CASILLA_COMERCIAL",LOG_ESTABLECIMIENTOMODIFICADO.CASILLA_COMERCIAL)
           sp.AgregarParametro("NOMBREESTABLECIMIENTO",LOG_ESTABLECIMIENTOMODIFICADO.NOMBREESTABLECIMIENTO)
           sp.AgregarParametro("TIPO_ESTABLECIMIENTO",LOG_ESTABLECIMIENTOMODIFICADO.TIPO_ESTABLECIMIENTO)
           sp.AgregarParametro("TIPO_FUNCIONAMIENTO",LOG_ESTABLECIMIENTOMODIFICADO.TIPO_FUNCIONAMIENTO)
            sp.AgregarParametro("CLASE", LOG_ESTABLECIMIENTOMODIFICADO.CLASE)
           sp.AgregarParametro("EXROL",LOG_ESTABLECIMIENTOMODIFICADO.EXROL)
           sp.AgregarParametro("NOMBRE_INFORMANTE",LOG_ESTABLECIMIENTOMODIFICADO.NOMBRE_INFORMANTE)
           sp.AgregarParametro("CARGO_INFORMANTE",LOG_ESTABLECIMIENTOMODIFICADO.CARGO_INFORMANTE)
           sp.AgregarParametro("CODA_FONO_INFORMANTE",LOG_ESTABLECIMIENTOMODIFICADO.CODA_FONO_INFORMANTE)
           sp.AgregarParametro("FONO_INFORMANTE",LOG_ESTABLECIMIENTOMODIFICADO.FONO_INFORMANTE)
           sp.AgregarParametro("CELULAR_INFORMANTE",LOG_ESTABLECIMIENTOMODIFICADO.CELULAR_INFORMANTE)
           sp.AgregarParametro("EMAIL_INFORMANTE",LOG_ESTABLECIMIENTOMODIFICADO.EMAIL_INFORMANTE)
           sp.AgregarParametro("NOMBRE_JEFE_RESPONSABLE",LOG_ESTABLECIMIENTOMODIFICADO.NOMBRE_JEFE_RESPONSABLE)
           sp.AgregarParametro("HABITACIONES_UNIDADES_HABITACIONALES",LOG_ESTABLECIMIENTOMODIFICADO.HABITACIONES_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("HABITACIONES_CAPACIDAD_MAXIMA",LOG_ESTABLECIMIENTOMODIFICADO.HABITACIONES_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("CABANAS_UNIDADES_HABITACIONALES",LOG_ESTABLECIMIENTOMODIFICADO.CABANAS_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("CABANAS_CAPACIDAD_MAXIMA",LOG_ESTABLECIMIENTOMODIFICADO.CABANAS_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("DEPARTAMENTOS_UNIDADES_HABITACIONALES",LOG_ESTABLECIMIENTOMODIFICADO.DEPARTAMENTOS_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("DEPARTAMENTOS_CAPACIDAD_MAXIMA",LOG_ESTABLECIMIENTOMODIFICADO.DEPARTAMENTOS_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("SITIOSDECAMPING_UNIDADES_HABITACIONALES",LOG_ESTABLECIMIENTOMODIFICADO.SITIOSDECAMPING_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("SITIOSDECAMPING_CAPACIDAD_MAXIMA",LOG_ESTABLECIMIENTOMODIFICADO.SITIOSDECAMPING_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("TOTAL_UNIDADES_HABITACIONALES",LOG_ESTABLECIMIENTOMODIFICADO.TOTAL_UNIDADES_HABITACIONALES)
           sp.AgregarParametro("TOTAL_CAPACIDAD_MAXIMA",LOG_ESTABLECIMIENTOMODIFICADO.TOTAL_CAPACIDAD_MAXIMA)
           sp.AgregarParametro("PERSONAL_OCUPADO_PERMANENTE_HOMBRE",LOG_ESTABLECIMIENTOMODIFICADO.PERSONAL_OCUPADO_PERMANENTE_HOMBRE)
           sp.AgregarParametro("PERSONAL_OCUPADO_PERMANENTE_MUJER",LOG_ESTABLECIMIENTOMODIFICADO.PERSONAL_OCUPADO_PERMANENTE_MUJER)
           sp.AgregarParametro("PERSONAL_OCUPADO_EVENTUAL_HOMBRE",LOG_ESTABLECIMIENTOMODIFICADO.PERSONAL_OCUPADO_EVENTUAL_HOMBRE)
           sp.AgregarParametro("PERSONAL_OCUPADO_EVENTUAL_MUJER",LOG_ESTABLECIMIENTOMODIFICADO.PERSONAL_OCUPADO_EVENTUAL_MUJER)
           sp.AgregarParametro("TOTAL_PERSONAL_OCUPADO_HOMBRE",LOG_ESTABLECIMIENTOMODIFICADO.TOTAL_PERSONAL_OCUPADO_HOMBRE)
           sp.AgregarParametro("TOTAL_PERSONAL_OCUPADO_MUJER",LOG_ESTABLECIMIENTOMODIFICADO.TOTAL_PERSONAL_OCUPADO_MUJER)
           sp.AgregarParametro("TOTAL_PERSONAL_OCUPADO",LOG_ESTABLECIMIENTOMODIFICADO.TOTAL_PERSONAL_OCUPADO)
           sp.AgregarParametro("FECHA_LEVANTAMIENTO",LOG_ESTABLECIMIENTOMODIFICADO.FECHA_LEVANTAMIENTO)
           sp.AgregarParametro("USUARIO_ACTUALIZACION",LOG_ESTABLECIMIENTOMODIFICADO.USUARIO_ACTUALIZACION)
           sp.AgregarParametro("FECHA_ACTUALIZACION",LOG_ESTABLECIMIENTOMODIFICADO.FECHA_ACTUALIZACION)
           sp.EjecutarProcedimiento()
       Catch ex As Exception
           Throw New Exception(ex.Message)
       End Try
   End Sub
#End Region
#REGION "METODO ELIMINAR"

   Public Sub Eliminar( PARAMETROS )
       Try
           Dim sp As New StoredProcedure_class("SP_LOG_ESTABLECIMIENTOMODIFICADO_Eliminar")
'Aqui deben definir los parametros necesarios
           sp.AgregarParametro("","")
'Fin de parametros necesarios
           sp.EjecutarProcedimiento()
       Catch ex As Exception
           Throw New Exception(ex.Message)
       End Try
   End Sub

#END REGION
#REGION "METODO LISTAR"

   Public Function Listar() as LOG_ESTABLECIMIENTOMODIFICADOENT()
       Try
           Dim dr as DataRow
           Dim dt as DataTable
           Dim i as Integer
           Dim sp As New StoredProcedure_class("SP_LOG_ESTABLECIMIENTOMODIFICADO_Listar")
           dt = sp.EjecutarProcedimiento().tables(0)
           Dim LOG_ESTABLECIMIENTOMODIFICADO(dt.Rows.count() - 1) as LOG_ESTABLECIMIENTOMODIFICADOENT
           i = 0
           for each dr in dt.rows
                LOG_ESTABLECIMIENTOMODIFICADO(i) = New LOG_ESTABLECIMIENTOMODIFICADOENT()
                LOG_ESTABLECIMIENTOMODIFICADO(i).ID_ENCUESTA = dr("ID_ENCUESTA")
                LOG_ESTABLECIMIENTOMODIFICADO(i).ROL = dr("ROL")
                LOG_ESTABLECIMIENTOMODIFICADO(i).DVROL = dr("DVROL")
                LOG_ESTABLECIMIENTOMODIFICADO(i).ANO = dr("ANO")
                LOG_ESTABLECIMIENTOMODIFICADO(i).PERIODO = dr("PERIODO")
                LOG_ESTABLECIMIENTOMODIFICADO(i).RUT = dr("RUT")
                LOG_ESTABLECIMIENTOMODIFICADO(i).NUI = dr("NUI")
                LOG_ESTABLECIMIENTOMODIFICADO(i).DVNUI = dr("DVNUI")
                LOG_ESTABLECIMIENTOMODIFICADO(i).CIIU = dr("CIIU")
                LOG_ESTABLECIMIENTOMODIFICADO(i).REGION_E = dr("REGION_E")
                LOG_ESTABLECIMIENTOMODIFICADO(i).PROVINCIA_E = dr("PROVINCIA_E")
                LOG_ESTABLECIMIENTOMODIFICADO(i).COMUNA_E = dr("COMUNA_E")
                LOG_ESTABLECIMIENTOMODIFICADO(i).GLOSA_COMUNA_E = dr("GLOSA_COMUNA_E")
                LOG_ESTABLECIMIENTOMODIFICADO(i).CALLE_E = dr("CALLE_E")
                LOG_ESTABLECIMIENTOMODIFICADO(i).NRO_E = dr("NRO_E")
                LOG_ESTABLECIMIENTOMODIFICADO(i).NRO_LOCAL_E = dr("NRO_LOCAL_E")
                LOG_ESTABLECIMIENTOMODIFICADO(i).CODA_FONO_E = dr("CODA_FONO_E")
                LOG_ESTABLECIMIENTOMODIFICADO(i).FONO_E = dr("FONO_E")
                LOG_ESTABLECIMIENTOMODIFICADO(i).CODA_FAX_E = dr("CODA_FAX_E")
                LOG_ESTABLECIMIENTOMODIFICADO(i).FAX_E = dr("FAX_E")
                LOG_ESTABLECIMIENTOMODIFICADO(i).EMAIL_E = dr("EMAIL_E")
                LOG_ESTABLECIMIENTOMODIFICADO(i).WEB_E = dr("WEB_E")
                LOG_ESTABLECIMIENTOMODIFICADO(i).CASILLA_COMERCIAL = dr("CASILLA_COMERCIAL")
                LOG_ESTABLECIMIENTOMODIFICADO(i).NOMBREESTABLECIMIENTO = dr("NOMBREESTABLECIMIENTO")
                LOG_ESTABLECIMIENTOMODIFICADO(i).TIPO_ESTABLECIMIENTO = dr("TIPO_ESTABLECIMIENTO")
                LOG_ESTABLECIMIENTOMODIFICADO(i).TIPO_FUNCIONAMIENTO = dr("TIPO_FUNCIONAMIENTO")
                LOG_ESTABLECIMIENTOMODIFICADO(i).CLASE = dr("CLASE")
                LOG_ESTABLECIMIENTOMODIFICADO(i).EXROL = dr("EXROL")
                LOG_ESTABLECIMIENTOMODIFICADO(i).NOMBRE_INFORMANTE = dr("NOMBRE_INFORMANTE")
                LOG_ESTABLECIMIENTOMODIFICADO(i).CARGO_INFORMANTE = dr("CARGO_INFORMANTE")
                LOG_ESTABLECIMIENTOMODIFICADO(i).CODA_FONO_INFORMANTE = dr("CODA_FONO_INFORMANTE")
                LOG_ESTABLECIMIENTOMODIFICADO(i).FONO_INFORMANTE = dr("FONO_INFORMANTE")
                LOG_ESTABLECIMIENTOMODIFICADO(i).CELULAR_INFORMANTE = dr("CELULAR_INFORMANTE")
                LOG_ESTABLECIMIENTOMODIFICADO(i).EMAIL_INFORMANTE = dr("EMAIL_INFORMANTE")
                LOG_ESTABLECIMIENTOMODIFICADO(i).NOMBRE_JEFE_RESPONSABLE = dr("NOMBRE_JEFE_RESPONSABLE")
                LOG_ESTABLECIMIENTOMODIFICADO(i).HABITACIONES_UNIDADES_HABITACIONALES = dr("HABITACIONES_UNIDADES_HABITACIONALES")
                LOG_ESTABLECIMIENTOMODIFICADO(i).HABITACIONES_CAPACIDAD_MAXIMA = dr("HABITACIONES_CAPACIDAD_MAXIMA")
                LOG_ESTABLECIMIENTOMODIFICADO(i).CABANAS_UNIDADES_HABITACIONALES = dr("CABANAS_UNIDADES_HABITACIONALES")
                LOG_ESTABLECIMIENTOMODIFICADO(i).CABANAS_CAPACIDAD_MAXIMA = dr("CABANAS_CAPACIDAD_MAXIMA")
                LOG_ESTABLECIMIENTOMODIFICADO(i).DEPARTAMENTOS_UNIDADES_HABITACIONALES = dr("DEPARTAMENTOS_UNIDADES_HABITACIONALES")
                LOG_ESTABLECIMIENTOMODIFICADO(i).DEPARTAMENTOS_CAPACIDAD_MAXIMA = dr("DEPARTAMENTOS_CAPACIDAD_MAXIMA")
                LOG_ESTABLECIMIENTOMODIFICADO(i).SITIOSDECAMPING_UNIDADES_HABITACIONALES = dr("SITIOSDECAMPING_UNIDADES_HABITACIONALES")
                LOG_ESTABLECIMIENTOMODIFICADO(i).SITIOSDECAMPING_CAPACIDAD_MAXIMA = dr("SITIOSDECAMPING_CAPACIDAD_MAXIMA")
                LOG_ESTABLECIMIENTOMODIFICADO(i).TOTAL_UNIDADES_HABITACIONALES = dr("TOTAL_UNIDADES_HABITACIONALES")
                LOG_ESTABLECIMIENTOMODIFICADO(i).TOTAL_CAPACIDAD_MAXIMA = dr("TOTAL_CAPACIDAD_MAXIMA")
                LOG_ESTABLECIMIENTOMODIFICADO(i).PERSONAL_OCUPADO_PERMANENTE_HOMBRE = dr("PERSONAL_OCUPADO_PERMANENTE_HOMBRE")
                LOG_ESTABLECIMIENTOMODIFICADO(i).PERSONAL_OCUPADO_PERMANENTE_MUJER = dr("PERSONAL_OCUPADO_PERMANENTE_MUJER")
                LOG_ESTABLECIMIENTOMODIFICADO(i).PERSONAL_OCUPADO_EVENTUAL_HOMBRE = dr("PERSONAL_OCUPADO_EVENTUAL_HOMBRE")
                LOG_ESTABLECIMIENTOMODIFICADO(i).PERSONAL_OCUPADO_EVENTUAL_MUJER = dr("PERSONAL_OCUPADO_EVENTUAL_MUJER")
                LOG_ESTABLECIMIENTOMODIFICADO(i).TOTAL_PERSONAL_OCUPADO_HOMBRE = dr("TOTAL_PERSONAL_OCUPADO_HOMBRE")
                LOG_ESTABLECIMIENTOMODIFICADO(i).TOTAL_PERSONAL_OCUPADO_MUJER = dr("TOTAL_PERSONAL_OCUPADO_MUJER")
                LOG_ESTABLECIMIENTOMODIFICADO(i).TOTAL_PERSONAL_OCUPADO = dr("TOTAL_PERSONAL_OCUPADO")
                LOG_ESTABLECIMIENTOMODIFICADO(i).FECHA_LEVANTAMIENTO = dr("FECHA_LEVANTAMIENTO")
                LOG_ESTABLECIMIENTOMODIFICADO(i).USUARIO_ACTUALIZACION = dr("USUARIO_ACTUALIZACION")
                LOG_ESTABLECIMIENTOMODIFICADO(i).FECHA_ACTUALIZACION = dr("FECHA_ACTUALIZACION")
                i = i + 1
           next
           return LOG_ESTABLECIMIENTOMODIFICADO
       Catch ex As Exception
           Throw New Exception(ex.Message)
       End Try
   End Function

#END REGION

#Region "OBTENER PARAMETROS"
    Public Function obtenerparametros(ByVal rol, ByVal encuesta) As DataTable
        Try
            Dim dt As DataTable
            Dim sp As New StoredProcedure_class("SP_LOG_ESTABLECIMIENTOMODIFICADO_obtenerparametros")
            sp.AgregarParametro("ROL", rol)
            sp.AgregarParametro("id_encuesta", encuesta)
            dt = sp.EjecutarProcedimiento().Tables(0)
            Return dt
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try

    End Function

#End Region

#Region "ACTUALIZAR DATOS DEL DIRECTORIO DESDE LA ENCUESTA"
    Public Sub ActualizarEmpEst_desdeEnc(ByVal EMPRESA As LOG_EMPRESAMODIFICADOENT, ByVal ESTABLECIMIENTO As LOG_ESTABLECIMIENTOMODIFICADOENT)
        Try

            Dim sp As New StoredProcedure_class("SP_LOG_ESTABLECIMIENTOMODIFICADO_ActualizarEmpEst_desdeEnc")

            ''Empresa
            sp.AgregarParametro("RUT", EMPRESA.RUT)
            sp.AgregarParametro("RAZONSOCIAL", EMPRESA.RAZONSOCIAL)
            sp.AgregarParametro("REPRESENTANTELEGAL", EMPRESA.REPRESENTANTELEGAL)
            sp.AgregarParametro("RUTREPRESENTANTELEGAL", EMPRESA.RUTREPRESENTANTELEGAL)
            sp.AgregarParametro("DVRUTREPRESENTANTELEGAL", EMPRESA.DVRUTREPRESENTANTELEGAL)

            ''Establecimiento
            sp.AgregarParametro("ROL", ESTABLECIMIENTO.ROL)
            sp.AgregarParametro("DVROL", ESTABLECIMIENTO.DVROL)
            sp.AgregarParametro("PERIODO", ESTABLECIMIENTO.PERIODO)
            sp.AgregarParametro("ANO", ESTABLECIMIENTO.ANO)
            sp.AgregarParametro("NOMBREESTABLECIMIENTO", ESTABLECIMIENTO.NOMBREESTABLECIMIENTO)
            sp.AgregarParametro("WEB_E", ESTABLECIMIENTO.WEB_E)
            sp.AgregarParametro("CALLE_E", ESTABLECIMIENTO.CALLE_E)
            sp.AgregarParametro("NRO_E", ESTABLECIMIENTO.NRO_E)
            sp.AgregarParametro("NRO_LOCAL_E", ESTABLECIMIENTO.NRO_LOCAL_E)
            sp.AgregarParametro("REGION_E", ESTABLECIMIENTO.REGION_E)
            sp.AgregarParametro("COMUNA_E", ESTABLECIMIENTO.COMUNA_E)
            sp.AgregarParametro("GLOSA_COMUNA_E", ESTABLECIMIENTO.GLOSA_COMUNA_E)
            sp.AgregarParametro("PROVINCIA_E", ESTABLECIMIENTO.PROVINCIA_E)
            sp.AgregarParametro("CASILLA_COMERCIAL", ESTABLECIMIENTO.CASILLA_COMERCIAL)
            sp.AgregarParametro("CODA_FONO_E", ESTABLECIMIENTO.CODA_FONO_E)
            sp.AgregarParametro("FONO_E", ESTABLECIMIENTO.FONO_E)
            sp.AgregarParametro("CODA_FAX_E", ESTABLECIMIENTO.CODA_FAX_E)
            sp.AgregarParametro("FAX_E", ESTABLECIMIENTO.FAX_E)
            sp.AgregarParametro("EMAIL_E", ESTABLECIMIENTO.EMAIL_E)
            sp.AgregarParametro("USUARIO_ACTUALIZACION", ESTABLECIMIENTO.USUARIO_ACTUALIZACION)

            sp.AgregarParametro("HABITACIONES_UNIDADES_HABITACIONALES", ESTABLECIMIENTO.HABITACIONES_UNIDADES_HABITACIONALES)
            sp.AgregarParametro("HABITACIONES_CAPACIDAD_MAXIMA", ESTABLECIMIENTO.HABITACIONES_CAPACIDAD_MAXIMA)
            sp.AgregarParametro("CABANAS_UNIDADES_HABITACIONALES", ESTABLECIMIENTO.CABANAS_UNIDADES_HABITACIONALES)
            sp.AgregarParametro("CABANAS_CAPACIDAD_MAXIMA", ESTABLECIMIENTO.CABANAS_CAPACIDAD_MAXIMA)
            sp.AgregarParametro("DEPARTAMENTOS_UNIDADES_HABITACIONALES", ESTABLECIMIENTO.DEPARTAMENTOS_UNIDADES_HABITACIONALES)
            sp.AgregarParametro("DEPARTAMENTOS_CAPACIDAD_MAXIMA", ESTABLECIMIENTO.DEPARTAMENTOS_CAPACIDAD_MAXIMA)
            sp.AgregarParametro("SITIOSDECAMPING_UNIDADES_HABITACIONALES", ESTABLECIMIENTO.SITIOSDECAMPING_UNIDADES_HABITACIONALES)
            sp.AgregarParametro("SITIOSDECAMPING_CAPACIDAD_MAXIMA", ESTABLECIMIENTO.SITIOSDECAMPING_CAPACIDAD_MAXIMA)
            sp.AgregarParametro("TOTAL_UNIDADES_HABITACIONALES", ESTABLECIMIENTO.TOTAL_UNIDADES_HABITACIONALES)
            sp.AgregarParametro("TOTAL_CAPACIDAD_MAXIMA", ESTABLECIMIENTO.TOTAL_CAPACIDAD_MAXIMA)

            sp.AgregarParametro("PERSONAL_OCUPADO_PERMANENTE_HOMBRE", ESTABLECIMIENTO.PERSONAL_OCUPADO_PERMANENTE_HOMBRE)
            sp.AgregarParametro("PERSONAL_OCUPADO_PERMANENTE_MUJER", ESTABLECIMIENTO.PERSONAL_OCUPADO_PERMANENTE_MUJER)
            sp.AgregarParametro("PERSONAL_OCUPADO_EVENTUAL_HOMBRE", ESTABLECIMIENTO.PERSONAL_OCUPADO_EVENTUAL_HOMBRE)
            sp.AgregarParametro("PERSONAL_OCUPADO_EVENTUAL_MUJER", ESTABLECIMIENTO.PERSONAL_OCUPADO_EVENTUAL_MUJER)
            sp.AgregarParametro("TOTAL_PERSONAL_OCUPADO_HOMBRE", ESTABLECIMIENTO.TOTAL_PERSONAL_OCUPADO_HOMBRE)
            sp.AgregarParametro("TOTAL_PERSONAL_OCUPADO_MUJER", ESTABLECIMIENTO.TOTAL_PERSONAL_OCUPADO_MUJER)
            sp.AgregarParametro("TOTAL_PERSONAL_OCUPADO", ESTABLECIMIENTO.TOTAL_PERSONAL_OCUPADO)

            sp.EjecutarProcedimiento()
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Sub
#End Region

#REGION "CONSTRUCTORES DE LA CLASE"
   Public Sub New()

   End Sub
#END REGION

end class
